feat(schema): modify the check that sets the column_default (defaultsTo) column definition
SpoonX/sails-generate-models pull request #9
Opened 2017-04-14 18:21 UTC by benomatis

This way it’s more elegant.

2017-04-15 08:04 UTC, RWOverdijk requested changes

2017-04-15 08:04 UTC, RWOverdijk commented on lib/schema.js
>      column.defaultsTo = definition.column_default;
For the sake of this PR (and getting you familiar with updating PRs) I'd like to request you to add curly braces.

2017-04-15 19:32 UTC, benomatis commented on lib/schema.js
>      column.defaultsTo = definition.column_default;
@RWOverdijk I just did that.

2017-04-16 18:23 UTC, RWOverdijk approved these changes

2017-04-16 18:23 UTC, merged